### PR TITLE
Debian: Fix jobs with multiple files or multiple formats

### PR DESCRIPTION
**Pull request by OdyX**
Bug-Redhat: https://bugzilla.redhat.com/show_bug.cgi?id=972242
Bug: https://github.com/apple/cups/issues/4348
Patch-Name: fixes-for-jobs-with-multiple-files-and-multiple-formats.patch

### CODE REVIEW

**Review by michaelrsweet — CHANGES_REQUESTED** [review]
This doesn't actually solve the problem, particularly if the files have explicit formats identified because they can't be auto-typed reliably.

We should probably pass "CONTENT_TYPEn" environment variables for each of the files in the job so that the backend can supply the formats the local cupsd is using.

**Comment by OdyX** [comment]
This is also shipped in Fedora for quite some time: https://src.fedoraproject.org/rpms/cups/blob/master/f/cups-ipp-multifile.patch

**Comment by michaelrsweet** [comment]
@OdyX Even so I'd feel more comfortable actually passing the original MIME media types - we've had enough bugs reported over the years over botched media types... :/

**Comment by OdyX** [comment]
This seems like an artefact from the 1.6 era. Let's not merge this (and I'll try removing it in Debian).

**Pull request closed without merging**
