### PR TITLE
Dark mode CSS

### PR DESCRIPTION
**Pull request by slinkouswasalreadytaken**
Added dark, more modern style based on Safari 14's dev tools

### CODE REVIEW

**Comment by michaelrsweet** [comment]
Thanks! There are other web interface changes that are coming but I'll make sure we incorporate this change for 2.4.0.

**Comment by jschwender** [comment]
Looks like the default mode is turned to dark mode, which i think is not a good idea: Dark modes are not proven to be better. Scientific research proves that this mode does not help office-eye-syndrom, and even Apple recommends it's use only for specific environment. Therefore, the right way to go is clearly to respect the desktop mode choosen by the end user, not to turn everything to dark, this is just chasing hype. Give the choice to the user.

**Comment by michaelrsweet** [comment]
@jschwender The final changes will use a media selector to honor the user's chosen color scheme, e.g.:

```
/* Dark mode overrides */
@media (prefers-color-scheme: dark) {
  ...
}
```

Whether people will be staring at the CUPS web interface in the dark, I don't know... I hope not! :)

**Comment by michaelrsweet** [comment]
[master 3daea66fd] Add dark mode CSS for web interface (Issue #152)

**Pull request closed without merging**
