### PR TITLE
add device_uri for found network printers (attempt 2)

### PR DESCRIPTION
**Pull request by Pro-pra**
from https://github.com/OpenPrinting/cups/pull/397

i add "title" and i see tooltip if mouse over printer name.

### CODE REVIEW

**Comment by zdohnal** [comment]
Hi @Pro-pra ,

thank you for the PR! I've verified that I can see device uri once I have my mouse cursor above the entry for network printers.
It would be great if you squashed your commits in the meantime.

LGTM. @michaelrsweet wdyt?

**Review by zdohnal — APPROVED** [review]
The changes look good to me, but please squash all commits into one.

**Comment by Pro-pra** [comment]
I don't know how to do it now

**Comment by zdohnal** [comment]
@Pro-pra you can find SHA ID of the last commit which is not yours (here 411b6136f450a5 - you can check by ```git log```) and then:

```
$ git reset --soft 411b6136f450a5
$ git commit -a
$ git push --force
```

In the commit step you will choose a commit message which covers all the changes you've done.

**Comment by Pro-pra** [comment]
and open new pull request?  
I think that a lot of PR is not needed for such a minor problem. Sorry.

**Comment by zdohnal** [comment]
No - there's no need for a new PR... otherwise I would've said it.

**Review by michaelrsweet — COMMENTED** [review]
LGTM

**Comment by zdohnal** [comment]
The PR pushed as commit https://github.com/OpenPrinting/cups/commit/23cef1c1374accc5d256b00b8afddffe645e4586 . Thank you for the PR!

**Pull request closed without merging**
