### PR TITLE
cups/dest.c: Remove an underscore from queue name if it is the last c…

### PR DESCRIPTION
**Pull request by zdohnal**
…haracter

It is a cosmetic issue to queue name looking better in print dialogs.

### CODE REVIEW

**Comment by michaelrsweet** [comment]
We'll need to do some regression testing on this as it could potentially cause issues, but I'm OK with this in theory.

**Comment by zdohnal** [comment]
@michaelrsweet I'll add a check for name length to prevent we don't have a empty string as a name.

**Comment by zdohnal** [comment]
Generates an warning:

```
dest.c: In function 'cups_queue_name':
dest.c:4370:5: warning: value computed is not used [-Wunused-value]
 4370 |     *nameptr--;
      |     ^~~~~~~~~~
```

Back to investigating...

**Comment by zdohnal** [comment]
Should be fine now.

**Pull request closed without merging**
