### PR TITLE
Add webui Polish translation

### PR DESCRIPTION
**Pull request by ppekala**

### CODE REVIEW

**Comment by zdohnal** [comment]
LGTM - however I wasn't able to find any Polish translations in your locale/cups_pl.po - is it intentional @ppekala ? This way Web UI will have Polish names, but any logs or CLI strings will be in English.

**Comment by ppekala** [comment]
There are some webserver responses translated, try searching for "cgi-bin" string:

% ./checkpo cups_pl.po
cups_pl.po: FAIL
    Too many untranslated messages (91 of 4027 or 2.3% are translated)

CLI tools and logs remain untranslated because I lack domain knowledge to provide translation I would consider good.

**Review by zdohnal — COMMENTED** [review]
Translation files looks good, but CI does not pass on "Running language API tests", which is different from the last commit, thus IMO the error is caused by this PR.
I will investigate the reason of the error and see whether a change will be requested.

**Review by zdohnal — CHANGES_REQUESTED** [review]
The test suite fails in this part because locale/cups_pl.po does not contain translations for Yes and No :) @ppekala can you update the the .po file with more translations? At least for Yes and No, but some other translations would be great as well, so Polish translation can be more useful.

**Review by zdohnal — APPROVED** [review]
CI fails on the known issues, acking the PR.

**Pull request merged**
