### PR TITLE
scheduler/printers.c: Add warning when loading printers

### PR DESCRIPTION
**Pull request by zdohnal**
Since drivers and raw queues going are deprecated and going to be
removed, this change will introduce a warning during cupsd's start.

This way we have all print queue installation options covered - lpadmin
and web ui were enhanced with warning in the past.

With this one merged, I would proceed with rc release - I hope I'll manage it this week (to match 2 week candency)

### CODE REVIEW

**Review by michaelrsweet — CHANGES_REQUESTED** [review]
So I'm ok in general with this, but I'd recommend just logging the general messages at the end and not the per-printer messages (or make those "debug" messages) in order to keep the extra logging to a minimum...

**Comment by zdohnal** [comment]
I've changed the log level of per-queues messages to DEBUG.

Thanks for the review!

**Comment by atsampson** [comment]
@zdohnal, this change causes the test suite to fail because two new warnings show up in the log:

```
FAIL: 14 warning messages, expected 12.
```

**Comment by zdohnal** [comment]
@atsampson thx, interesting that tests on PR didn't catch that... fixed by 2857cd8c5 .

**Comment by atsampson** [comment]
@zdohnal - that's fixed it - thanks!

**Pull request merged**
