### PR TITLE
added more translations and fixed older ones

### PR DESCRIPTION
**Pull request by jschwender**

### CODE REVIEW

**Comment by kloczek** [comment]
IMO it would be good to rewtite translations support to use proper gettext support. oinstead custom processing .po files.

**Comment by michaelrsweet** [comment]
@kloczek If GNU gettext was universally available, worked well on all supported operating systems (particularly macOS), and was provided under a friendly license (i.e. *not* GPL3), I might agree with you. But since none of those things are true, the decision I made 20 years ago to use the PO format (which is widely supported by translation tools) with my own localization code that handles loading both PO and strings (macOS/iOS) files.

The GNU gettext API is also strongly tied to the current locale, which poses problems for programs like cupsd that want to report localized error messages to network clients that may be using a different language than the server.

**Comment by kloczek** [comment]
> If GNU gettext was universally available, worked well on all supported operating systems (particularly macOS

Many MOX distribution components are alreaduu using gettext because it is only i18n support in the original source tree.
Yes, gettext/1i8n support workx on MOX as well.

**Comment by michaelrsweet** [comment]
@kloczek GNU gettext does not respect the language preferences on macOS.

**Comment by kloczek** [comment]
Which one languages used now in cups are not supported on MOX?
Gettext support has nothing to do with languages.
Only uses difftent encodings.
As MOX supports utf8 all what is necessary to do is not accept .po files with non-utf8 encodings.
```
[tkloczko@barrel cups-2.3.3op2]$ grep charset= locale/*.po
locale/cups_ca.po:"Content-Type: text/plain; charset=UTF-8\n"
locale/cups_cs.po:"Content-Type: text/plain; charset=UTF-8\n"
locale/cups_de.po:"Content-Type: text/plain; charset=UTF-8\n"
locale/cups_en.po:"Content-Type: text/plain; charset=UTF-8\n"
locale/cups_es.po:"Content-Type: text/plain; charset=UTF-8\n"
locale/cups_fr.po:"Content-Type: text/plain; charset=UTF-8\n"
locale/cups_it.po:"Content-Type: text/plain; charset=UTF-8\n"
locale/cups_ja.po:"Content-Type: text/plain; charset=UTF-8\n"
locale/cups_pt_BR.po:"Content-Type: text/plain; charset=UTF-8\n"
locale/cups_ru.po:"Content-Type: text/plain; charset=UTF-8\n"
locale/cups_zh_CN.po:"Content-Type: text/plain; charset=UTF-8\n"
```

**Comment by michaelrsweet** [comment]
@kloczek GNU gettext uses the current locale to choose a message catalog while macOS uses a more complex prioritized language list. Applications that use gettext on macOS don't actually get localized unless you manually set the `LANG` or `LC_xxx` environment variables.

**Comment by kloczek** [comment]
> GNU gettext uses the current locale to choose a message catalog while macOS uses a more complex prioritized language list. Applications that use gettext on macOS don't actually get localized unless you manually set the LANG or LC_xxx environment variables.

And it still has nothing to do with gettext support on soiurce tree level of some projects which are using gettext.
That support has nothing to do with alghorith of finding exact .mo file basing on locale settings
In exact i18n implementation on code level you don't need to use env variables.

**Comment by michaelrsweet** [comment]
@kloczek This will be my last response on this subject.

OP CUPS uses the same .po files that other projects do. Translation tools and translators that know how to edit .po can edit CUPS .po files, same as any other project. The fact that CUPS does not use GPL3 GNU gettext to read or "compile" those files doesn't matter, and we *will not* be changing that.

**Comment by michaelrsweet** [comment]
@jschwender Looks like there is a minor conflict due to the changes in ippeveprinter - can you fix that (Github isn't cooperating with me) and then I'll take care of merging it. Thanks!

**Comment by jschwender** [comment]
i tried to solve it, but it still shows unsolved - did it work or not?

**Comment by jschwender** [comment]
@michaelrsweet can you merge it now? I followed the Resolve conflicts button, but it is unclear to me what the result is, it still says there is a conflict. If this is a dead end, you may discard the whole pull request and i can start another pull request?

**Comment by michaelrsweet** [comment]
@jschwender I'm not sure what is going wrong with this; can you rebase your copy and then do a fresh pull request? Thanks!

**Pull request closed without merging**
