### PR TITLE
Fix leak of data.devices in cups_enum_dests

### PR DESCRIPTION
**Pull request by jwatt**
Encountered in https://bugzilla.mozilla.org/show_bug.cgi?id=1747952

### CODE REVIEW

**Review by michaelrsweet — APPROVED** [review]
LGTM, thanks!

**Comment by jwatt** [comment]
Thanks for all your work on CUPS over the years. Hugely appreciated!

**Comment by zdohnal** [comment]
Hi @jwatt ,

thank you for the PR! I'm merging it now.

**Comment by jwatt** [comment]
Thanks @zdohnal, much appreciated!

**Pull request merged**
