### PR TITLE
Update pt-BR translation

### PR DESCRIPTION
**Pull request by guilhermgonzaga**
Hello.

I'm willing to update the portuguese translations for cups, but it's a lot of work, just over 2500 msgs left.
I would like to know if you impose a line length limit, or there is some build step before submitting the PR.
I'm using checkpo.

### CODE REVIEW

**Comment by zdohnal** [comment]
Hi @guilhermgonzaga ,

thank you for the PR! IMHO we don't impose a line length limit regarding code style in .po files, however there are string length limits in the library - max length for formatted strings (const message + variable values) is 2046, and for non-formatted string it is 8188.

AFAIK there is no additional build step if I understand Makefile correctly - we generate cups.strings from cups_en.po, so localized .pos don't seem to be used during build.

@michaelrsweet please let me know if it is correct - I've checked this by looking into the code.

**Comment by michaelrsweet** [comment]
@zdohnal Correct, you just put the new .po file in the locale directory and the configure/install steps will use it automatically.

**Comment by guilhermgonzaga** [comment]
Ok, thanks for the tip.

I added more translations in the meantime, but that's all I can translate for now. PR is ready.

**Review by zdohnal — APPROVED** [review]
LGTM!

**Pull request merged**
